packages:
  - "core"
  - "web"
  - "packages/*"

catalog:
  "@effect/platform": ^0.69.11
  effect: ^3.10.6
  typescript: ^5.6.3
  vitest: ^1.6.0
  prettier: ^3.2.5
  prettier-plugin-tailwindcss: ^0.5.14
  autoprefixer: ^10.4.20
  postcss: ^8.4.47
  tailwindcss: ^3.4.13
  react: ^18.3.1
  react-dom: ^18.3.1
